- searchinsortedarray.java
> My code to commit

- count_negativematrix.java
- divide_twoint.java
count negative in matrix .Code completed
> second code to comit

- divide_two.java
> my second to be done

- Search.java
- searchtarget
#6 
Please let me contribute .Also let me know about any changes to be made
> Search the element 

- Repeated Substring Pattern
Repeated Substring Pattern java solution #29 
name - Srushti Johari
UCE2021429 
TY Comp 
Cummins college of engineering Pune
> Create Repeated Substring Pattern #29

- Reverse_sublist_of_linklist.java
> Added code for reverse sublist of a linked list

- merge 2 binary trees
Solution for merge 2 binary trees java #68
> Create merge 2 binary trees

- CountofSmallerNumbersAfterSelf.java
- CountofSmallerNumbersAfterSelfSolution.java
- LRUCache.java
#112 Count of Smaller Numbers After Self issue solved
> Count of Smaller Numbers After Self #112

- CountofSmallerNumbersAfterSelf.java
- LRUCache.java
> #63 LRU Cache

- CountofSmallerNumbersAfterSelf.java
- HighScore.java
- LRUCache.java
> #154 High Score

- VerticalOrderTraversalOfBT.txt
#98 Solution to issue Vertical Order Traversal Of Binary Tree
Isha Baviskar
baviskarisha2194@gmail.com
> Vertical order traversal of bt

- SolutionToStickLengthsProblem.txt
#144 - Solution to Stick Lengths Problem by Isha Baviskar
> Solution to Stick Lengths Problem - #144

- CountofSmallerNumbersAfterSelf.java
- LRUCache.java
- MinimumTotalCosttoMakeArraysUnequal.java
#83 Minimum Total Cost to Make Arrays Unequal issue solved.
> #83 Minimum Total Cost to Make Arrays Unequal

- transpose.java
Committing changes to #198 Pascal's Triangle
> #198 Pascal's Triangle

- PlanetsAndKingdoms.java
- RoundTrip.java
Aditi Sharma
UCE2021661
TY CSE, CCOEW
Solved issue #153 using java programming language
> Aditi3004 patch 3

- issue#11.py
Closes issue #11
Created a program using Python, which identifies the middle element in the entered list an
d prints the node in an orderly manner.
> Middle element of linked list

- PlanetsAndKingdoms.java
- RemovalGame.java
Aditi Sharma
UCE2021661
TY CSE,CCOEW
Solved the issue #151 using java programming language.
> Aditi3004 patch 2

- Rotate List
Rotate List #41 solution java O(n) time complexity
> Create Rotate List #41

- issue#12_SubarraySumsDivisiblebyK.py
- search.java
Added solution of Subarray Sums Divisible by K [#12](https://github.com/Google-Developer-Student-Club-CCOEW/Competitive-Programming-2023-GDSC-CUMMINS-X-GDSC-MMCOE/issues/12)
> Added #issue12_SubarraySumsDivisiblebyK.py Solution

- Intersection of 2 Linked Lists
Intersection of 2 linked lists #23 java solution
> Create Intersection of 2 Linked Lists #23

- #152_Projects.java
- #168_Teleporters Path.cpp
- Course_Schedule_#87.java
Added Solution to Course Schedule #87
Akanksha Kale
TY IT Cummins
UEC2021139
Kindly review the PR and add **_hacktoberfest,  hacktoberfest-accepted labels._**
Thank you!
> Akanksha1131/course schedule #87

- MinStack.txt
> Branch for min stack

- #167_Hamiltonian_Flights.cpp
Added Solution to Hamiltonian Flights #167
Akanksha Kale
TY IT Cummins
UEC2021139
Kindly review the PR and add **_hacktoberfest,  hacktoberfest-accepted labels._**
Thank you!
> Akanksha1131/Hamiltonian flights #167

- Find the town judge.java
> Code for find the Town Judge

- issue#15_ReverseLinkedList.py
Added solution of Reverse Linked List #15
> Added solution of #15

- First non-repeating character in a stream #61.txt
#61
For this problem I'm first counting the frequency of the character with the help of unordered map and if it is less than 0 then I'm pushing that character in a vector & then  appending the 0th index character of the vector in the answer string. And if the frequency is greater than 0 then I'm first erasing that character from the vector, after erasing I'm checking if the vector is empty If it is then I'm appending '#' to the answer string otherwise I'm appending the 0th index character of  vector to answer string.
Time Complexity : O(n)
Space Complexity : O(n)
> Issue #61 : Added Code for first Non-Repeating Character in a Stream 

- Index of the First Occurrence.java
> Added Solution of Find the Index of the First Occurrence in a String

- Find the kth largest number
#57 
Please accept my contribution
>  Find the kth largest number

- DeepCopyLinkedListWithRandomPointer.txt
> Copy List with Random Pointer

- Search in sorted array
#16
Here is the solution in java .
>  Search in sorted array

- verifying Alien Dictionary.java
> Added Solution for Verifying Alien Dictionary

- Employee Importance.java
> Added Solution for Employee Importance

- ArrayDescription.txt
#150 Solution to Array Description Issue #150
By Tejal Hajari
> Solution to Array Description Issue

- Reorganize String  #79.txt
#79 
First I have calculated the frequency of each character. Then have placed character with high frequency on alternate positions, and then the rest of the character. If the arrange is not possible then I have returned an empty string "".
> Issue #79 : Added Code for Reorganizing String in C++

- TextJustification.java
- teleporters_path.cpp
Added solution to Added solution Text Justification #42
Akanksha Kale 
TY IT
Cummins
UEC2021139
Thank you!
> Added solution Text Justification #42

- LongestPalindromicSubstring.txt
> Branch for longest palindromic substring

- LetterCombinationsOfPhoneNo.java
- QueueUsingStacks.java
> Letter Combinations of a Phone Number

- QueueUsingStacks.java
> Implementation Of Queue Using Stacks

- issue74.txt
> merge 2D arrays by summing values

- Stack Using Queue.java
> Added Code for Implementation of Stack Using Queue

- Backspace String Compare.txt
> Backspace String Compare

- trapping.java
> Trapping rainwater new

- SortItemsByGroupsRespectingDependices.cpp
> Added: Sort Items by Groups Respecting Dependencies

- CountGoodNodesInBT.java
> Count Good Nodes in Binary Tree

- LongestStringChain.java
> Longest String Chain

- prefix.java
> Longest comman prefix

- BinaryToInt.java
> Added code for Binary Number in a linked list to Integer

- MinSubarraaySum.java
> Added code for Minimum size Subarray Sum

- buddyStrings.java
> Added code for Buddy Strings

- Excel Sheet Column Title.java
> Create Excel Sheet Column Title.java

- Minimum Remove to Make Valid Parentheses.java
> Create  Minimum Remove to Make Valid Parentheses.java

- Product of Array Except Self.java
> Create Product of Array Except Self.java

- .vscode/c_cpp_properties.json
- .vscode/launch.json
- .vscode/settings.json
- distinct_subsequences.cpp
I solved the problem using the bottom-up approach of DP. I hope this solution helps!
> #40 Distinct subsequences solved

- Sum_of_four_values.cpp
- strange_printer.cpp
I solved this issue using DP. I hope this solution helps!!
> #43 Strange printer problem solved

- k_binary_tree.cpp
- zigzag.cpp
Added solution for issue #71 in cpp
> Solution to issue #71

- zigzag.cpp
Added the solution for the zigzag problem. issue #34
> solution for issue #34 - zigzag conversion

- comman.java
> Codeforlca

- LVP.java
> Longest valid parenthesis

- duplicates.java
> Remove duplicates

- network_delay_time.cpp
Added solution for issue #91 in cpp.
> Solution to issue #91
